version: '1.0'
services:
  - name: db
    type: mariadb
    version: 10.4
    configuration: StandAlone
    database: wordpress
    username: wordpress
    # Ask password on create
    userPassword: null
    password: null
    ports:
      - 3306
    remoteAccess: false
    comments:
        username: Database will be created with the same name
    deployTo:
      - main

  - name: cache
    type: redis
    version: 5.0
    remoteAccess: false
    ports:
      - 6379
    deployTo:
      - main

  - name: blog
    type: phpApache
    version: 7.2
    source:
      type: download
      url: https://wordpress.org/latest.zip
    extensions:
      - mysqli
      - opcache
      - gd
      - zip
      - soap
    pecl:
      - redis
    ports:
      - 80
    remoteAccess: false
    volumes:
      - directory: $MAIN_PATH/wp-content
        sync: true
    configFiles:
      - dest: $MAIN_PATH/wp-config.php
        src: ./configs/wp-config.php
      - dest: $MAIN_PATH/db-config.php
        src: ./configs/db-config.php
      - dest: $MAIN_PATH/wp-content/db.php
        src: ./configs/db.php
      - dest: $MAIN_PATH/.htaccess
        src: ./configs/.htaccess
    globalDeps: |
      apt-get install less mariadb-client
      curl https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -o /usr/local/bin/wp
      chmod +x /usr/local/bin/wp
      cp -r $MAIN_PATH/wp-content /var/www/wp-content-tmp
      chown -R www-data:www-data /var/www
    localDeps: cp -r /var/www/wp-content-tmp/* $MAIN_PATH/wp-content
    initialCommands: |
      cd $MAIN_PATH
      wp core install --url={{=service('blog').getBalancerDomain()}} --title='"$WP_TITLE"' --admin_user=$WP_ADMIN_USERNAME --admin_password=$WP_ADMIN_PASSWORD --admin_email=$WP_ADMIN_EMAIL --allow-root
      wp plugin install redis-cache --activate --allow-root
      wp redis enable --allow-root
    env:
      WP_TITLE: null
      WP_ADMIN_USERNAME: null
      WP_ADMIN_PASSWORD: null
      WP_ADMIN_EMAIL: null
      DB_REPLICATION: off
    comments:
      env:
        WP_TITLE: The title of your Wordpress website
        WP_ADMIN_USERNAME: Username of administrator account
        WP_ADMIN_PASSWORD: Password of administrator account
        WP_ADMIN_EMAIL: Email of administrator account
        DB_REPLICATION: Set it to "on" when you scale Database to MasterSlave configuration
    deployTo:
      - main

  - name: balancer
    type: haproxy
    version: latest
    ports:
      - 80
      - 443
    remoteAccess: true
    serviceFiles:
      - name: blog
        sticky: true
    deployTo:
      - main

  - name: adminer
    type: docker
    image: adminer
    version: latest
    ports:
      - 8080
    remoteAccess: true
    env:
      ADMINER_DEFAULT_SERVER: "{{=service('db').getMasterAlias()}}"
    deployTo:
      - main

hosts:
  - name: main
    requirements:
      cores: 1
      memory: 2
